[workspace]

exclude = [
	"substrate",
	"subxt",
	"webpki",
	"ring",
	"native-nostd-hasher",
	"standalone/pruntime",
]

members = [
	"common/types",
	"standalone/executor",
	"standalone/rpc",
    "standalone/node",
	"standalone/runtime",
	"standalone/phost",
	"pallets/phala",
	"pallets/mining_staking",
	"pallets/bridge",
	"pallets/mining_staking",
	"scripts/toml-upgrade-version",
	"scripts/debug-cli"
]

resolver = "2"
