[package]
authors = ['Phala Network']
edition = '2018'
name = 'pallet-claim'
version = "2.0.1"
license = "Apache 2.0"
homepage = "https://phala.network/"
repository = "https://github.com/Phala-Network/phala-blockchain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.102", default-features = false }
codec = { package = "parity-scale-codec", version = "2.1", default-features = false }
rustc-hex = { version = "2.0.1", default-features = false }
frame-support = { version = "3.0.0", default-features = false, path = "../../substrate/frame/support" }
frame-system = { version = "3.0.0", default-features = false, path = "../../substrate/frame/system" }
sp-std = { version = "3.0.0", default-features = false, path = "../../substrate/primitives/std" }
sp-io = { version = "3.0.0", default-features = false, path = "../../substrate/primitives/io" }
sp-runtime = {  version = "3.0.0", default-features = false, path = "../../substrate/primitives/runtime" }
log = { version = "0.4.14", default-features = false }

[dependencies.pallet-balances]
default-features = false
version = "3.0.0"
path = "../../substrate/frame/balances"

[dev-dependencies]
hex-literal = "0.2.1"
pallet-timestamp = { version = "3.0.0", path = "../../substrate/frame/timestamp" }
codec = { package = "parity-scale-codec", version = "2.1", default-features = false }
sp-core = { version = "3.0.0", default-features = false, path = "../../substrate/primitives/core" }
sp-io = { version = "3.0.0", default-features = false, path = "../../substrate/primitives/io" }
sp-runtime = {  version = "3.0.0", default-features = false, path = "../../substrate/primitives/runtime"  }

[features]
default = ['std']
std = [
    "serde/std",
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "log/std",
]
try-runtime = ["frame-support/try-runtime"]
