[package]
name = "app"
version = "0.0.1"
authors = ["jasl"]
build = "build.rs"

[dependencies]
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts  = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
mio       = "0.7"

rocket         = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["json"]}
rocket_codegen = "0.4.5"
rocket_cors = "0.5.2"
serde     = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.1.0"
log = "0.4"
env_logger = "0.8"
hex = "0.4.2"

[dev-dependencies]
ring-compat = "0.0.1"
base64 = "0.12.3"
hex-literal = "0.3.1"

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
# sgx_alloc = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_backtrace = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_backtrace_sys = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_build_helper = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_cov = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_crypto_helper = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_demangle = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_libc = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_rand = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_rand_derive = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_serialize = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_serialize_derive = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_serialize_derive_internals = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tcrypto = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tcrypto_helper = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tdh = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tkey_exchange = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tprotected_fs = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_trts = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tse = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tseal = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tstd = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_tunittest = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
sgx_types = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_ucrypto = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
# sgx_unwind = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
sgx_urts = { git = "https://github.com/Phala-Network/incubator-teaclave-sgx-sdk.git" }
