[package]
name = "pallet-session-benchmarking"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME sessions pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { version = "3.0.0", default-features = false, path = "../../../substrate/primitives/std" }
sp-session = { version = "3.0.0", default-features = false, path = "../../../substrate/primitives/session" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../../substrate/primitives/runtime" }
frame-system = { version = "3.0.0", default-features = false, path = "../../../substrate/frame/system" }
frame-benchmarking = { version = "3.1.0", default-features = false, path = "../../../substrate/frame/benchmarking" }
frame-support = { version = "3.0.0", default-features = false, path = "../../../substrate/frame/support" }
pallet-staking = { package = "phala-staking", version = "3.0.0", default-features = false, features = ["runtime-benchmarks"], path = "../../staking" }
pallet-session = { version = "3.0.0", default-features = false, path = "../../../substrate/frame/session" }
rand = { version = "0.7.2", default-features = false }

[dev-dependencies]
serde = { version = "1.0.101" }
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
sp-core = { version = "3.0.0", path = "../../../substrate/primitives/core" }
pallet-staking-reward-curve = { version = "3.0.0", path = "../../../substrate/frame/staking/reward-curve" }
sp-io ={ version = "3.0.0", path = "../../../substrate/primitives/io" }
pallet-timestamp = { version = "3.0.0", path = "../../../substrate/frame/timestamp" }
pallet-balances = { version = "3.0.0", path = "../../../substrate/frame/balances" }
frame-election-provider-support = { version = "3.0.0", path = "../../../substrate/frame/election-provider-support" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-session/std",
	"sp-runtime/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-election-provider-support/std",
	"pallet-staking/std",
	"pallet-session/std",
]
